language: node_js
node_js: lts/*
cache: yarn
sudo: true
install: yarn

before_install:
  - chmod +x ./build-env.sh
  - ./build-env.sh

before_deploy:
  - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
  - echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
  - sudo apt-get update && sudo apt-get install -y --allow-unauthenticated cf-cli

script:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x ./deploy.sh
  - CI=false yarn build

deploy:
  - provider: script
    script: sudo ./deploy.sh
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(develop|stage|production)$
    skip_cleanup: true

notifications:
  slack:
    rooms:
      - cognitive-app:iSEB3UaVj2jziPUrzAzWJ70x
    on_failure: always
    on_success: always
